#Find the patient(s) who spent the most total money.
select patients.Patient_ID, patients.Patient_Name, sum(billing.Amount) as total_money from patients
join appointments
on
appointments.Patient_ID = patients.Patient_ID
join billing
on
billing.Appointment_ID=appointments.Appointment_ID
group by patients.Patient_ID, patients.Patient_Name
order by total_money desc
limit 1;


#List doctors who have treated more than 10 unique patients.
select doctors.Doctor_ID, doctors.Doctor_Name, count(distinct appointments.Patient_ID) as number_of_patients from doctors
join appointments
on
appointments.Doctor_ID=doctors.Doctor_ID
group by doctors.Doctor_ID,doctors.Doctor_Name
having number_of_patients > 10
order by number_of_patients asc;


#Create a view showing patient name, doctor name, appointment date, and bill amount.
CREATE VIEW PatientAppointmentSummary AS
select patients.Patient_Name, doctors.Doctor_Name, appointments.Appointment_Date,billing.Amount from patients
join appointments
on
appointments.Patient_ID=patients.Patient_ID
join doctors
on
doctors.Doctor_ID=appointments.Doctor_ID
join billing
on
billing.Appointment_ID=appointments.Appointment_ID;



#Find the most active doctor (most appointments overall).
select doctors.Doctor_ID, doctors.Doctor_Name, count(appointments.Appointment_ID) as total_appointments from doctors
join appointments
on
appointments.Doctor_ID=doctors.Doctor_ID
group by doctors.Doctor_ID, doctors.Doctor_Name
order by total_appointments desc
limit 1;


#Show monthly revenue generated by the hospital.
select date_format(Payment_Date, '%y-%m') as month, sum(Amount) as total_revenue from billing
group by month
order by total_revenue desc;


#Find patients who have only missed (No Show) appointments.
select patients.Patient_ID, patients.Patient_Name, appointments.Appointment_Status from patients
join appointments
on
appointments.Patient_ID=patients.Patient_ID
group by patients.Patient_ID,patients.Patient_Name,appointments.Appointment_Status
having COUNT(*) = SUM(appointments.Appointment_Status = 'No Show');


#Rank appointments by bill amount (highest to lowest).
select appointments.Appointment_ID , billing.Amount, rank() over  (order by billing.Amount desc) as billing_rank from appointments
join billing 
on
billing.Appointment_ID=appointments.Appointment_ID;



#Show percentage of appointments by status.
select appointments.Appointment_Status, round((count(*)  * 100)/(select count(Appointment_ID) from appointments),2) as percentage from appointments
group by appointments.Appointment_Status
order by percentage desc;



#For each doctor, list their last appointment date.
select doctors.Doctor_ID,doctors.Doctor_Name, max(appointments.Appointment_Date) as last_appointment from doctors
join appointments
on
appointments.Doctor_ID=doctors.Doctor_ID
group by doctors.Doctor_ID,doctors.Doctor_Name